// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRtE18O5VFavm8Gh5VpoA_Zcq5BTgz9E',
    appId: '1:806116824746:web:8c8a375ff430840c4e22d3',
    messagingSenderId: '806116824746',
    projectId: 'mini-chat-2025',
    authDomain: 'mini-chat-2025.firebaseapp.com',
    storageBucket: 'mini-chat-2025.firebasestorage.app',
    measurementId: 'G-K4ZSH4D1PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6m5QdI2i8XsJlji4m4PjhI2sH2wWsns',
    appId: '1:806116824746:android:ad29878cdaca9eb34e22d3',
    messagingSenderId: '806116824746',
    projectId: 'mini-chat-2025',
    storageBucket: 'mini-chat-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnNcw0vuSPLMWiI8ZmZh3rQp60zvOurM',
    appId: '1:806116824746:ios:9e7a629dbc88dd2a4e22d3',
    messagingSenderId: '806116824746',
    projectId: 'mini-chat-2025',
    storageBucket: 'mini-chat-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPnNcw0vuSPLMWiI8ZmZh3rQp60zvOurM',
    appId: '1:806116824746:ios:9e7a629dbc88dd2a4e22d3',
    messagingSenderId: '806116824746',
    projectId: 'mini-chat-2025',
    storageBucket: 'mini-chat-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCRtE18O5VFavm8Gh5VpoA_Zcq5BTgz9E',
    appId: '1:806116824746:web:fc098e214de98e534e22d3',
    messagingSenderId: '806116824746',
    projectId: 'mini-chat-2025',
    authDomain: 'mini-chat-2025.firebaseapp.com',
    storageBucket: 'mini-chat-2025.firebasestorage.app',
    measurementId: 'G-Y57W6T9JHN',
  );
}
